// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by dev/tasks/generate-all. DO NOT EDIT.
// +generated:types
// krm.group: networkservices.cnrm.cloud.google.com
// krm.version: v1alpha1
// proto.service: google.cloud.networkservices.v1
// resource: NetworkServicesServiceBinding:ServiceBinding
// resource: NetworkServicesLbRouteExtension:LbRouteExtension

package v1alpha1

// +kcc:proto=google.cloud.networkservices.v1.ExtensionChain
type ExtensionChain struct {
	// Required. The name for this extension chain.
	//  The name is logged as part of the HTTP request logs.
	//  The name must conform with RFC-1034, is restricted to lower-cased letters,
	//  numbers and hyphens, and can have a maximum length of 63 characters.
	//  Additionally, the first character must be a letter and the last a letter or
	//  a number.
	// +kcc:proto:field=google.cloud.networkservices.v1.ExtensionChain.name
	Name *string `json:"name,omitempty"`

	// Required. Conditions under which this chain is invoked for a request.
	// +kcc:proto:field=google.cloud.networkservices.v1.ExtensionChain.match_condition
	MatchCondition *ExtensionChain_MatchCondition `json:"matchCondition,omitempty"`

	// Required. A set of extensions to execute for the matching request.
	//  At least one extension is required.
	//  Up to 3 extensions can be defined for each extension chain
	//  for `LbTrafficExtension` resource.
	//  `LbRouteExtension` and `LbEdgeExtension` chains are limited to 1 extension
	//  per extension chain.
	// +kcc:proto:field=google.cloud.networkservices.v1.ExtensionChain.extensions
	Extensions []ExtensionChain_Extension `json:"extensions,omitempty"`
}

// +kcc:proto=google.cloud.networkservices.v1.ExtensionChain.MatchCondition
type ExtensionChain_MatchCondition struct {
	// Required. A Common Expression Language (CEL) expression that is used to
	//  match requests for which the extension chain is executed.
	//
	//  For more information, see [CEL matcher language
	//  reference](https://cloud.google.com/service-extensions/docs/cel-matcher-language-reference).
	// +kcc:proto:field=google.cloud.networkservices.v1.ExtensionChain.MatchCondition.cel_expression
	CelExpression *string `json:"celExpression,omitempty"`
}
